### ISSUE TITLE
CreativeNoClip

### ISSUE THREAD

**Issue by ghost** [TISUnion/TISCarpet113#22]
由CreativeNoClip引起的故事：看tiscarpet里面这个功能描述要在客户端也要开启此项功能，然后我按照README.txt里面的操作我将自己的1.13客户端也弄成了tiscarpet，进游戏后能使用该功能，请问下要怎么解决在能用tiscarpet的基础上用模组（投影，minihud之类的）

**Comment by ghost** [comment]
是要在tiscarpet的基础上安装rift吗
qwq（逃

**Comment by Fallen-Breath** [comment]
TIS carpet 为 jarmod，不支持使用 mod 加载器加载
不过由于 TIS carpet 使用了 fabric carpet 的协议，你可以使用 1.14 及以后的 fabric carpet 客户端配合跨版本连接服务器的手段进行登录使用
当然你可以催更 Kahzerx 的 [RiftedCarpet](https://github.com/Kahzerx/RiftedCarpet)
