### ISSUE TITLE
/schedule

### ISSUE THREAD

**Issue by ghost** [TISUnion/TISCarpet113#26]
/schedule命令结合数据包以及计分榜就可以实现自定义单位的在线时长计分榜，就不用像原版自带的/scoreboard里的play_one_minute计分项只能以刻为单位查看和展示计分榜，但这个命令是在1.14+才加入的，1.13没有这个命令，本人又菜的出奇，也不会自己开发，所以想来问问tiscarpet会考虑加入这一命令吗（白嫖的嫌疑+++，逃

**Comment by Fallen-Breath** [comment]
计分板不也可以加减乘除得到自定义时间单位吗

**Comment by ghost** [comment]
那个只是对玩家进行单次的加减乘除吧，就比如这个/scoreboard players operation @a scb_a /= @a scb_b，把名为scb_a的榜上的所有玩家的分数除以scb_b上所有玩家对应的分数，得到的结果会赋给scb_a。
我当时也是想着利用计分板自带的加减乘除（这个operation）来实现，让以play_one_minute为计分项的榜除以另一个所有玩家值为20*60=1200且不变的榜，来得到以分钟为单位的在线时长的榜，但是按照上面指令的逻辑，明显不行，然后查wiki查到了schedule指令(创个计分榜，然后写个数据包，里面放个mcfunction文件，在上面写几条指令实现每隔60s就对在线玩家在该计分榜上+1,如果要剔除假人的在线时长，步骤就再稍微麻烦一点)，当时用1.15.2客户端试成功了，但等到进自己的服里面一试，才发现没这个schedule，所以想着来问问看

**Comment by Fallen-Breath** [comment]
1. 创建每 gt 自增的计分板项 A
2. A 在数值到了 1200 时，A 清零，为所有在线玩家的在线分钟榜 +1

以及，注意这里不是计分板/数据包帮助中心

**Comment by ghost** [comment]
要自增的话也还是需要循环的吧，额，好的，只是问一下
